name: Create Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  actions: read
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Verify build output
        run: |
          echo "Checking if dist folder exists and contains files..."
          ls -la dist/
          echo "Build verification complete"

      - name: Create zip archive
        run: |
          cd dist
          # Remove any .DS_Store files and other unwanted files
          find . -name ".DS_Store" -delete
          find . -name "*.map" -delete
          # Create the zip file
          zip -r ../fast-note-chrome-${{ github.ref_name }}.zip .
          cd ..
          # Create a checksum file
          sha256sum fast-note-chrome-${{ github.ref_name }}.zip > fast-note-chrome-${{ github.ref_name }}.zip.sha256

      - name: Create release and upload assets
        run: |
          gh release create ${{ github.ref_name }} \
            fast-note-chrome-${{ github.ref_name }}.zip \
            fast-note-chrome-${{ github.ref_name }}.zip.sha256 \
            --title "Release ${{ github.ref_name }}" \
            --notes "## Changes
          
          Please see the commit history for detailed changes.
          
          ## Installation
          
          1. Download the \`fast-note-chrome-${{ github.ref_name }}.zip\` file
          2. Extract the contents
          3. Open Chrome and go to \`chrome://extensions/\`
          4. Enable \"Developer mode\"
          5. Click \"Load unpacked\" and select the extracted folder
          
          ## Verification
          
          You can verify the integrity of the download using the SHA256 checksum:
          \`\`\`
          sha256sum fast-note-chrome-${{ github.ref_name }}.zip
          \`\`\`"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
